### ISSUE TITLE
Integrating txthings with a client

### ISSUE THREAD

**Issue by erbdex** [siskin/txThings#3]
Excuse my being new to the reactor way of things, but how does one go about making say 200 CoAP requests using txthings library? Specifically- do i run and stop reactor after every request? I get a feeling that this isn't the way to go as the overhead of starting stopping the reactor thread with every request will be fairly massive.

**Comment by siskin** [comment]
TxThings is based on Twisted framework, which is an asynchronous I/O framework. Async frameworks require that software using them is written in a particular, non-blocking way. The reactor is an event loop, and should be a main loop of your program. The advantage of using event loop is that requests are not blocking - you can make 200 requests simultaneously.
