### ISSUE TITLE
Does txThings support DTLS?

### ISSUE THREAD

**Issue by louisZL** [siskin/txThings#9]
Does txThings support DTLS?

**Comment by siskin** [comment]
DTLS is unfortunately not supported. I don't know any Python CoAP library with DTLS support. You may try using Eclipse Californium (Java).

**Comment by louisZL** [comment]
Thanks a lot!



long.zhang@lumiunited.com
 
From: Maciej Wasilak
Date: 2015-12-24 22:41
To: siskin/txThings
CC: louisZL
Subject: Re: [txThings] Does txThings support DTLS? (#9)
DTLS is unfortunately not supported. I don't know any Python CoAP library with DTLS support. You may try using Eclipse Californium (Java).
